#include "arrow.h"
#include "colors.h"

const uint32_t RIGHT_ARROW_TEXTURE[BUTTON_ARROW_WIDTH * BUTTON_ARROW_HEIGHT] = {
    [0 ... 119] = C_TRANS,

    C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_NVY,C_NVY,C_NVY,C_NVY,C_NVY,C_NVY,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,
    C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_NVY,C_BLU,C_BLU,C_BLU,C_BLU,C_BLU,C_BLU,C_NVY,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,
    // Wiersz 6-7
    C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_NVY,C_BLU,C_SKY,C_SKY,C_SKY,C_SKY,C_SKY,C_SKY,C_BLU,C_NVY,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,
    C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_NVY,C_BLU,C_SKY,C_CYN,C_CYN,C_CYN,C_CYN,C_CYN,C_CYN,C_SKY,C_BLU,C_NVY,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,
    // Wiersz 8-10
    C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_NVY,C_BLU,C_SKY,C_CYN,C_CYN,C_CYN,C_CYN,C_CYN,C_CYN,C_CYN,C_CYN,C_SKY,C_BLU,C_NVY,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,
    C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_NVY,C_BLU,C_SKY,C_CYN,C_CYN,C_CYN,C_CYN,C_CYN,C_CYN,C_CYN,C_CYN,C_CYN,C_CYN,C_SKY,C_BLU,C_NVY,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,
    C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_NVY,C_BLU,C_SKY,C_CYN,C_CYN,C_CYN,C_CYN,C_CYN,C_CYN,C_CYN,C_CYN,C_CYN,C_CYN,C_CYN,C_CYN,C_SKY,C_BLU,C_NVY,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,
    // Wiersz 11-15
    C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_NVY,C_BLU,C_SKY,C_CYN,C_CYN,C_CYN,C_CYN,C_CYN,C_CYN,C_CYN,C_CYN,C_CYN,C_CYN,C_CYN,C_CYN,C_CYN,C_CYN,C_SKY,C_BLU,C_NVY,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,
    C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_NVY,C_BLU,C_SKY,C_CYN,C_CYN,C_CYN,C_CYN,C_CYN,C_CYN,C_CYN,C_CYN,C_CYN,C_CYN,C_CYN,C_CYN,C_CYN,C_CYN,C_CYN,C_CYN,C_SKY,C_BLU,C_NVY,C_TRANS,C_TRANS,C_TRANS,C_TRANS,
    C_TRANS,C_TRANS,C_TRANS,C_NVY,C_BLU,C_SKY,C_CYN,C_CYN,C_CYN,C_CYN,C_CYN,C_CYN,C_CYN,C_CYN,C_CYN,C_CYN,C_CYN,C_CYN,C_CYN,C_CYN,C_CYN,C_CYN,C_CYN,C_CYN,C_SKY,C_BLU,C_NVY,C_TRANS,C_TRANS,C_TRANS,
    C_TRANS,C_TRANS,C_NVY,C_BLU,C_SKY,C_CYN,C_CYN,C_CYN,C_CYN,C_CYN,C_CYN,C_CYN,C_CYN,C_CYN,C_CYN,C_CYN,C_CYN,C_CYN,C_CYN,C_CYN,C_CYN,C_CYN,C_CYN,C_CYN,C_CYN,C_SKY,C_BLU,C_NVY,C_TRANS,C_TRANS,
    C_TRANS,C_NVY,C_BLU,C_SKY,C_CYN,C_CYN,C_CYN,C_CYN,C_CYN,C_CYN,C_CYN,C_CYN,C_CYN,C_CYN,C_CYN,C_CYN,C_CYN,C_CYN,C_CYN,C_CYN,C_CYN,C_CYN,C_CYN,C_CYN,C_CYN,C_CYN,C_SKY,C_BLU,C_NVY,C_TRANS,
    // Wiersz 16-20
    C_NVY,C_BLU,C_SKY,C_CYN,C_CYN,C_CYN,C_CYN,C_CYN,C_CYN,C_CYN,C_CYN,C_CYN,C_CYN,C_CYN,C_CYN,C_CYN,C_CYN,C_CYN,C_CYN,C_CYN,C_CYN,C_CYN,C_CYN,C_CYN,C_CYN,C_CYN,C_CYN,C_SKY,C_BLU,C_NVY,
    C_NVY,C_BLU,C_SKY,C_CYN,C_CYN,C_CYN,C_CYN,C_CYN,C_CYN,C_CYN,C_CYN,C_CYN,C_CYN,C_CYN,C_CYN,C_CYN,C_CYN,C_CYN,C_CYN,C_CYN,C_CYN,C_CYN,C_CYN,C_CYN,C_CYN,C_CYN,C_CYN,C_SKY,C_BLU,C_NVY,
    C_NVY,C_BLU,C_SKY,C_SKY,C_SKY,C_SKY,C_SKY,C_SKY,C_SKY,C_SKY,C_SKY,C_SKY,C_SKY,C_SKY,C_SKY,C_SKY,C_SKY,C_SKY,C_SKY,C_SKY,C_SKY,C_SKY,C_SKY,C_SKY,C_SKY,C_SKY,C_SKY,C_SKY,C_BLU,C_NVY,
    C_NVY,C_BLU,C_BLU,C_BLU,C_BLU,C_BLU,C_BLU,C_BLU,C_BLU,C_BLU,C_BLU,C_BLU,C_BLU,C_BLU,C_BLU,C_BLU,C_BLU,C_BLU,C_BLU,C_BLU,C_BLU,C_BLU,C_BLU,C_BLU,C_BLU,C_BLU,C_BLU,C_BLU,C_BLU,C_NVY,
    C_NVY,C_NVY,C_NVY,C_NVY,C_NVY,C_NVY,C_NVY,C_NVY,C_NVY,C_NVY,C_NVY,C_NVY,C_NVY,C_NVY,C_NVY,C_NVY,C_NVY,C_NVY,C_NVY,C_NVY,C_NVY,C_NVY,C_NVY,C_NVY,C_NVY,C_NVY,C_NVY,C_NVY,C_NVY,C_NVY,

	[630 ... 899] = C_TRANS
};


const uint32_t LEFT_ARROW_TEXTURE[BUTTON_ARROW_WIDTH * BUTTON_ARROW_HEIGHT] = {
    [0 ... 269] = C_TRANS,

    C_NVY,C_NVY,C_NVY,C_NVY,C_NVY,C_NVY,C_NVY,C_NVY,C_NVY,C_NVY,C_NVY,C_NVY,C_NVY,C_NVY,C_NVY,C_NVY,C_NVY,C_NVY,C_NVY,C_NVY,C_NVY,C_NVY,C_NVY,C_NVY,C_NVY,C_NVY,C_NVY,C_NVY,C_NVY,C_NVY,
    C_NVY,C_BLU,C_BLU,C_BLU,C_BLU,C_BLU,C_BLU,C_BLU,C_BLU,C_BLU,C_BLU,C_BLU,C_BLU,C_BLU,C_BLU,C_BLU,C_BLU,C_BLU,C_BLU,C_BLU,C_BLU,C_BLU,C_BLU,C_BLU,C_BLU,C_BLU,C_BLU,C_BLU,C_BLU,C_NVY,
    C_NVY,C_BLU,C_SKY,C_SKY,C_SKY,C_SKY,C_SKY,C_SKY,C_SKY,C_SKY,C_SKY,C_SKY,C_SKY,C_SKY,C_SKY,C_SKY,C_SKY,C_SKY,C_SKY,C_SKY,C_SKY,C_SKY,C_SKY,C_SKY,C_SKY,C_SKY,C_SKY,C_SKY,C_BLU,C_NVY,
    C_NVY,C_BLU,C_SKY,C_CYN,C_CYN,C_CYN,C_CYN,C_CYN,C_CYN,C_CYN,C_CYN,C_CYN,C_CYN,C_CYN,C_CYN,C_CYN,C_CYN,C_CYN,C_CYN,C_CYN,C_CYN,C_CYN,C_CYN,C_CYN,C_CYN,C_CYN,C_CYN,C_SKY,C_BLU,C_NVY,
    C_NVY,C_BLU,C_SKY,C_CYN,C_CYN,C_CYN,C_CYN,C_CYN,C_CYN,C_CYN,C_CYN,C_CYN,C_CYN,C_CYN,C_CYN,C_CYN,C_CYN,C_CYN,C_CYN,C_CYN,C_CYN,C_CYN,C_CYN,C_CYN,C_CYN,C_CYN,C_CYN,C_SKY,C_BLU,C_NVY,

    C_TRANS,C_NVY,C_BLU,C_SKY,C_CYN,C_CYN,C_CYN,C_CYN,C_CYN,C_CYN,C_CYN,C_CYN,C_CYN,C_CYN,C_CYN,C_CYN,C_CYN,C_CYN,C_CYN,C_CYN,C_CYN,C_CYN,C_CYN,C_CYN,C_CYN,C_CYN,C_SKY,C_BLU,C_NVY,C_TRANS,
    C_TRANS,C_TRANS,C_NVY,C_BLU,C_SKY,C_CYN,C_CYN,C_CYN,C_CYN,C_CYN,C_CYN,C_CYN,C_CYN,C_CYN,C_CYN,C_CYN,C_CYN,C_CYN,C_CYN,C_CYN,C_CYN,C_CYN,C_CYN,C_CYN,C_CYN,C_SKY,C_BLU,C_NVY,C_TRANS,C_TRANS,
    C_TRANS,C_TRANS,C_TRANS,C_NVY,C_BLU,C_SKY,C_CYN,C_CYN,C_CYN,C_CYN,C_CYN,C_CYN,C_CYN,C_CYN,C_CYN,C_CYN,C_CYN,C_CYN,C_CYN,C_CYN,C_CYN,C_CYN,C_CYN,C_CYN,C_SKY,C_BLU,C_NVY,C_TRANS,C_TRANS,C_TRANS,
    C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_NVY,C_BLU,C_SKY,C_CYN,C_CYN,C_CYN,C_CYN,C_CYN,C_CYN,C_CYN,C_CYN,C_CYN,C_CYN,C_CYN,C_CYN,C_CYN,C_CYN,C_CYN,C_CYN,C_SKY,C_BLU,C_NVY,C_TRANS,C_TRANS,C_TRANS,C_TRANS,
    C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_NVY,C_BLU,C_SKY,C_CYN,C_CYN,C_CYN,C_CYN,C_CYN,C_CYN,C_CYN,C_CYN,C_CYN,C_CYN,C_CYN,C_CYN,C_CYN,C_CYN,C_SKY,C_BLU,C_NVY,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,

    C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_NVY,C_BLU,C_SKY,C_CYN,C_CYN,C_CYN,C_CYN,C_CYN,C_CYN,C_CYN,C_CYN,C_CYN,C_CYN,C_CYN,C_CYN,C_SKY,C_BLU,C_NVY,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,
    C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_NVY,C_BLU,C_SKY,C_CYN,C_CYN,C_CYN,C_CYN,C_CYN,C_CYN,C_CYN,C_CYN,C_CYN,C_CYN,C_SKY,C_BLU,C_NVY,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,
    C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_NVY,C_BLU,C_SKY,C_CYN,C_CYN,C_CYN,C_CYN,C_CYN,C_CYN,C_CYN,C_CYN,C_SKY,C_BLU,C_NVY,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,
    C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_NVY,C_BLU,C_SKY,C_CYN,C_CYN,C_CYN,C_CYN,C_CYN,C_CYN,C_SKY,C_BLU,C_NVY,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,
    C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_NVY,C_BLU,C_SKY,C_SKY,C_SKY,C_SKY,C_SKY,C_SKY,C_BLU,C_NVY,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,
    C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_NVY,C_BLU,C_BLU,C_BLU,C_BLU,C_BLU,C_BLU,C_NVY,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,
    C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_NVY,C_NVY,C_NVY,C_NVY,C_NVY,C_NVY,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,

	[780 ... 899] = C_TRANS
};
