#include "bullet.h"
#include "colors.h"

const uint32_t BULLET_TEXTURE[BULLET_WIDTH*BULLET_HEIGHT] = {

		// Wiersz 0
		C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_AURA_L, C_AURA_L, C_AURA_L, C_AURA_L, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS,

		// Wiersz 1
		C_TRANS, C_TRANS, C_AURA_L, C_AURA_M, C_PLAS_ORG, C_PLAS_ORG, C_FIRE_RED, C_FIRE_RED, C_FIRE_DK, C_AURA_L, C_TRANS, C_TRANS, C_TRANS,

		// Wiersz 2
		C_TRANS, C_AURA_L, C_AURA_M, C_CORE_GOLD, C_PLAS_BRT, C_PLAS_ORG, C_PLAS_ORG, C_FIRE_RED, C_FIRE_RED, C_FIRE_DK, C_AURA_M, C_TRANS, C_TRANS,

		// Wiersz 3
		C_TRANS, C_AURA_M, C_CORE_GOLD, C_CORE_GOLD, C_PLAS_BRT, C_PLAS_BRT, C_PLAS_ORG, C_PLAS_ORG, C_FIRE_RED, C_FIRE_RED, C_FIRE_DK, C_AURA_L, C_TRANS,

		// Wiersz 4
		C_TRANS, C_CORE_GOLD, C_CORE_WHT, C_CORE_WHT, C_CORE_GOLD, C_PLAS_BRT, C_PLAS_BRT, C_PLAS_ORG, C_PLAS_ORG, C_FIRE_RED, C_FIRE_RED, C_FIRE_DK, C_AURA_M,

		// Wiersz 5
		C_TRANS, C_CORE_GOLD, C_CORE_WHT, C_CORE_WHT, C_CORE_GOLD, C_PLAS_BRT, C_PLAS_BRT, C_PLAS_ORG, C_PLAS_ORG, C_FIRE_RED, C_FIRE_RED, C_FIRE_DK, C_AURA_M,

		// Wiersz 6
		C_TRANS, C_AURA_M, C_CORE_GOLD, C_CORE_GOLD, C_PLAS_BRT, C_PLAS_BRT, C_PLAS_ORG, C_PLAS_ORG, C_FIRE_RED, C_FIRE_RED, C_FIRE_DK, C_AURA_L, C_TRANS,

		// Wiersz 7
		C_TRANS, C_AURA_L, C_AURA_M, C_CORE_GOLD, C_PLAS_BRT, C_PLAS_ORG, C_PLAS_ORG, C_FIRE_RED, C_FIRE_RED, C_FIRE_DK, C_AURA_M, C_TRANS, C_TRANS,

		// Wiersz 8
		C_TRANS, C_TRANS, C_AURA_L, C_AURA_M, C_PLAS_ORG, C_PLAS_ORG, C_FIRE_RED, C_FIRE_RED, C_FIRE_DK, C_AURA_L, C_TRANS, C_TRANS, C_TRANS,

		// Wiersz 9
		C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_AURA_L, C_AURA_L, C_AURA_L, C_AURA_L, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS

};

const uint32_t ENEMY_BULLET_TEXTURE[BULLET_WIDTH*BULLET_HEIGHT] = {

    // Wiersz 0 (Góra - wąski ślad)
    C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TOXIC2, C_TOXIC2, C_TRANS, C_TRANS, C_TRANS, C_TRANS,

    // Wiersz 1
    C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TOXIC2, C_TOXIC2, C_ACID2, C_ACID2, C_ACID2, C_TOXIC2, C_TRANS, C_TRANS, C_TRANS,

    // Wiersz 2
    C_TRANS, C_TRANS, C_TOXIC2, C_TOXIC2, C_ACID2, C_ACID2, C_NEON2, C_NEON2, C_NEON2, C_ACID2, C_TOXIC2, C_TRANS, C_TRANS,

    // Wiersz 3
    C_TRANS, C_TOXIC2, C_ACID2, C_ACID2, C_NEON2, C_NEON2, C_NEON2, C_NEON2, C_NEON2, WHITE, WHITE, C_TOXIC2, C_TRANS,

    // Wiersz 4 (Środek - najjaśniejszy, głowica po prawej)
    C_TOXIC2, C_ACID2, C_NEON2, C_NEON2, C_NEON2, C_NEON2, WHITE, WHITE, WHITE, WHITE, WHITE, C_NEON2, C_TRANS,

    // Wiersz 5 (Środek - lustrzane odbicie wiersza 4)
    C_TOXIC2, C_ACID2, C_NEON2, C_NEON2, C_NEON2, C_NEON2, WHITE, WHITE, WHITE, WHITE, WHITE, C_NEON2, C_TRANS,

    // Wiersz 6
    C_TRANS, C_TOXIC2, C_ACID2, C_ACID2, C_NEON2, C_NEON2, C_NEON2, C_NEON2, C_NEON2, WHITE, WHITE, C_TOXIC2, C_TRANS,

    // Wiersz 7
    C_TRANS, C_TRANS, C_TOXIC2, C_TOXIC2, C_ACID2, C_ACID2, C_NEON2, C_NEON2, C_NEON2, C_ACID2, C_TOXIC2, C_TRANS, C_TRANS,

    // Wiersz 8
    C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TOXIC2, C_TOXIC2, C_ACID2, C_ACID2, C_ACID2, C_TOXIC2, C_TRANS, C_TRANS, C_TRANS,

    // Wiersz 9 (Dół)
    C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TOXIC2, C_TOXIC2, C_TRANS, C_TRANS, C_TRANS, C_TRANS
};

