#include "enemy.h"
#include "colors.h"

const uint32_t ENEMY_TEXTURE[ENEMY_WIDTH * ENEMY_HEIGHT] = {

    // Kolumna 0
    C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TOXIC_GLW, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TOXIC_GLW, C_TRANS, C_TRANS, C_TRANS,

    // Kolumna 1
    C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_ALIEN_DK, C_ALIEN_DK, C_ALIEN_DK, C_ALIEN_DK, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TOXIC_GLW, C_TOXIC_GLW, C_TRANS, C_TRANS,

    // Kolumna 2
    C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_ALIEN_DK, C_ALIEN_DK, C_ALIEN_DK, C_ALIEN_MAIN, C_ALIEN_MAIN, C_ALIEN_LGT, C_ALIEN_MAIN, C_ALIEN_DK, C_ALIEN_DK, C_ALIEN_DK, C_TOXIC_GLW, C_TOXIC_GLW, C_TRANS, C_TRANS, C_TRANS, C_TRANS,

    // Kolumna 3
    C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_ALIEN_DK, C_ALIEN_DK, C_ALIEN_DK, C_ALIEN_DK, C_ALIEN_DK, C_ALIEN_MAIN, C_ALIEN_MAIN, C_ALIEN_LGT, C_ALIEN_LGT, C_ALIEN_MAIN, C_ALIEN_LGT, C_ALIEN_MAIN, C_ALIEN_MAIN, C_ALIEN_LGT, C_ALIEN_MAIN, C_ALIEN_DK, C_ALIEN_DK, C_TOXIC_GLW, C_TRANS, C_TRANS, C_TRANS, C_TRANS,

    // Kolumna 4
    C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_ALIEN_DK, C_ALIEN_MAIN, C_ALIEN_MAIN, C_ALIEN_LGT, C_ALIEN_LGT, C_ALIEN_LGT, C_ALIEN_MAIN, C_ALIEN_MAIN, C_ALIEN_LGT, C_TRANS, C_TRANS, C_ALIEN_LGT, C_ALIEN_MAIN, C_ALIEN_DK, C_ALIEN_DK, C_ALIEN_MAIN, C_ALIEN_LGT, C_ALIEN_MAIN, C_ALIEN_DK, C_TOXIC_GLW, C_TOXIC_GLW, C_TRANS, C_TRANS, C_TRANS,

    // Kolumna 5
    C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_ALIEN_DK, C_ALIEN_MAIN, C_ALIEN_MAIN, C_ALIEN_LGT, C_ALIEN_MAIN, C_ALIEN_MAIN, C_ALIEN_MAIN, C_ALIEN_MAIN, C_ALIEN_LGT, C_ALIEN_MAIN, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_ALIEN_MAIN, C_ALIEN_DK, C_TRANS, C_ALIEN_DK, C_ALIEN_MAIN, C_ALIEN_DK, C_TRANS, C_TOXIC_GLW, C_TOXIC_GLW, C_TOXIC_GLW, C_TRANS, C_TRANS,

    // Kolumna 6
    C_TRANS, C_TRANS, C_TRANS, C_ALIEN_DK, C_ALIEN_MAIN, C_ALIEN_LGT, C_ALIEN_MAIN, C_ALIEN_DK, C_ALIEN_DK, C_ALIEN_DK, C_ALIEN_DK, C_ALIEN_MAIN, C_ALIEN_LGT, C_ALIEN_MAIN, C_ALIEN_DK, C_ALIEN_DK, C_ALIEN_DK, C_ALIEN_DK, C_ALIEN_MAIN, C_ALIEN_DK, C_TRANS, C_TRANS, C_ALIEN_DK, C_TRANS, C_TRANS, C_TOXIC_GLW, C_TOXIC_GLW, C_TOXIC_GLW, C_TOXIC_GLW, C_TRANS,

    // Kolumna 7
    C_TRANS, C_TRANS, C_ALIEN_DK, C_ALIEN_MAIN, C_ALIEN_LGT, C_ALIEN_DK, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_ALIEN_DK, C_ALIEN_MAIN, C_ALIEN_DK, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_ALIEN_DK, C_ALIEN_MAIN, C_ALIEN_DK, C_TRANS, C_TRANS, C_ALIEN_DK, C_ALIEN_MAIN, C_ALIEN_DK, C_TRANS, C_TOXIC_GLW, C_TOXIC_GLW, C_TRANS,

    // Kolumna 8
    C_TRANS, C_ALIEN_DK, C_ALIEN_MAIN, C_ALIEN_LGT, C_ALIEN_DK, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_ALIEN_DK, C_ALIEN_MAIN, C_ENG_PURP, C_ALIEN_DK, C_TRANS, C_TRANS, C_ALIEN_DK, C_ALIEN_MAIN, C_TOXIC_GLW, C_ALIEN_MAIN, C_ALIEN_DK, C_TRANS, C_TRANS, C_ALIEN_DK, C_ALIEN_MAIN, C_TOXIC_GLW, C_TOXIC_GLW, C_TRANS, C_TRANS,

    // Kolumna 9
    C_ALIEN_DK, C_ALIEN_MAIN, C_ALIEN_LGT, C_ALIEN_DK, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_ALIEN_DK, C_ALIEN_MAIN, C_ENG_PURP, C_ALIEN_MAIN, C_ALIEN_DK, C_ALIEN_DK, C_ALIEN_MAIN, C_TOXIC_GLW, C_TOXIC_GLW, C_TOXIC_GLW, C_ALIEN_MAIN, C_ALIEN_DK, C_TRANS, C_TRANS, C_ALIEN_DK, C_ALIEN_MAIN, C_TOXIC_GLW, C_TRANS, C_TRANS,

    // Kolumna 10
    C_ALIEN_DK, C_ALIEN_MAIN, C_ALIEN_DK, C_TRANS, C_TRANS, C_TRANS, C_ALIEN_DK, C_ALIEN_DK, C_ALIEN_DK, C_ALIEN_DK, C_ALIEN_DK, C_ALIEN_MAIN, C_ALIEN_LGT, C_ENG_PURP, C_ALIEN_LGT, C_ALIEN_MAIN, C_ALIEN_MAIN, C_ALIEN_LGT, C_ALIEN_MAIN, C_ALIEN_DK, C_ALIEN_DK, C_ALIEN_MAIN, C_TOXIC_GLW, C_ALIEN_MAIN, C_ALIEN_DK, C_TRANS, C_ALIEN_DK, C_ALIEN_MAIN, C_TOXIC_GLW, C_TRANS,

    // Kolumna 11
    C_ALIEN_DK, C_ALIEN_MAIN, C_ALIEN_DK, C_TRANS, C_TRANS, C_ALIEN_DK, C_ALIEN_MAIN, C_ALIEN_LGT, C_ALIEN_LGT, C_ALIEN_LGT, C_ALIEN_MAIN, C_ALIEN_LGT, C_TOXIC_GLW, C_ENG_PURP, C_TOXIC_GLW, C_ALIEN_LGT, C_ALIEN_MAIN, C_ALIEN_MAIN, C_ALIEN_DK, C_TRANS, C_TRANS, C_ALIEN_DK, C_ALIEN_MAIN, C_ENG_CORE, C_TOXIC_GLW, C_ALIEN_MAIN, C_ALIEN_DK, C_TOXIC_GLW, C_TRANS, C_TRANS,

    // Kolumna 12
    C_ALIEN_DK, C_ALIEN_MAIN, C_ALIEN_DK, C_TRANS, C_ALIEN_DK, C_ALIEN_MAIN, C_ALIEN_LGT, C_TOXIC_GLW, C_TOXIC_GLW, C_TOXIC_GLW, C_ALIEN_LGT, C_ALIEN_MAIN, C_ALIEN_LGT, C_ENG_PURP, C_ALIEN_LGT, C_ALIEN_MAIN, C_ALIEN_DK, C_ALIEN_DK, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_ALIEN_DK, C_ALIEN_MAIN, C_TOXIC_GLW, C_ENG_CORE, C_TOXIC_GLW, C_TOXIC_GLW, C_TOXIC_GLW, C_TRANS,

    // Kolumna 13
    C_ALIEN_DK, C_ALIEN_MAIN, C_ALIEN_DK, C_TRANS, C_ALIEN_DK, C_ALIEN_MAIN, C_ALIEN_LGT, C_TOXIC_GLW, C_ENG_PURP, C_TOXIC_GLW, C_ALIEN_LGT, C_ALIEN_MAIN, C_ALIEN_LGT, C_ENG_PURP, C_ALIEN_LGT, C_ALIEN_MAIN, C_ALIEN_DK, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_ALIEN_DK, C_ALIEN_MAIN, C_TOXIC_GLW, C_ENG_CORE, C_TOXIC_GLW, C_TOXIC_GLW, C_TOXIC_GLW,

    // Srodek

    // Kolumna 14
    C_ALIEN_DK, C_ALIEN_MAIN, C_ALIEN_DK, C_ALIEN_DK, C_ALIEN_MAIN, C_ALIEN_LGT, C_ALIEN_LGT, C_TOXIC_GLW, C_ENG_PURP, C_TOXIC_GLW, C_ALIEN_LGT, C_ALIEN_LGT, C_ALIEN_MAIN, C_ENG_PURP, C_ALIEN_MAIN, C_ALIEN_LGT, C_ALIEN_DK, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_ALIEN_DK, C_ALIEN_MAIN, C_TOXIC_GLW, C_ENG_CORE, C_TOXIC_GLW, C_TOXIC_GLW,

    // Kolumna 15
    C_ALIEN_DK, C_ALIEN_MAIN, C_ALIEN_DK, C_ALIEN_DK, C_ALIEN_MAIN, C_ALIEN_LGT, C_ALIEN_LGT, C_TOXIC_GLW, C_ENG_PURP, C_TOXIC_GLW, C_ALIEN_LGT, C_ALIEN_LGT, C_ALIEN_MAIN, C_ENG_PURP, C_ALIEN_MAIN, C_ALIEN_LGT, C_ALIEN_DK, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_ALIEN_DK, C_ALIEN_MAIN, C_TOXIC_GLW, C_ENG_CORE, C_TOXIC_GLW, C_TOXIC_GLW,

    // Prawa

    // Kolumna 16
    C_ALIEN_DK, C_ALIEN_MAIN, C_ALIEN_DK, C_TRANS, C_ALIEN_DK, C_ALIEN_MAIN, C_ALIEN_LGT, C_TOXIC_GLW, C_ENG_PURP, C_TOXIC_GLW, C_ALIEN_LGT, C_ALIEN_MAIN, C_ALIEN_LGT, C_ENG_PURP, C_ALIEN_LGT, C_ALIEN_MAIN, C_ALIEN_DK, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS,

    // Kolumna 17
    C_ALIEN_DK, C_ALIEN_MAIN, C_ALIEN_DK, C_TRANS, C_ALIEN_DK, C_ALIEN_MAIN, C_ALIEN_LGT, C_TOXIC_GLW, C_TOXIC_GLW, C_TOXIC_GLW, C_ALIEN_LGT, C_ALIEN_MAIN, C_ALIEN_LGT, C_ENG_PURP, C_ALIEN_LGT, C_ALIEN_MAIN, C_ALIEN_DK, C_ALIEN_DK, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS,

    // Kolumna 18
    C_ALIEN_DK, C_ALIEN_MAIN, C_ALIEN_DK, C_TRANS, C_TRANS, C_ALIEN_DK, C_ALIEN_MAIN, C_ALIEN_LGT, C_ALIEN_LGT, C_ALIEN_LGT, C_ALIEN_MAIN, C_ALIEN_LGT, C_TOXIC_GLW, C_ENG_PURP, C_TOXIC_GLW, C_ALIEN_LGT, C_ALIEN_MAIN, C_ALIEN_MAIN, C_ALIEN_DK, C_TRANS, C_TRANS, C_ALIEN_DK, C_ALIEN_MAIN, C_ENG_CORE, C_TOXIC_GLW, C_ALIEN_MAIN, C_ALIEN_DK, C_TOXIC_GLW, C_TRANS, C_TRANS,

    // Kolumna 19
    C_ALIEN_DK, C_ALIEN_MAIN, C_ALIEN_DK, C_TRANS, C_TRANS, C_TRANS, C_ALIEN_DK, C_ALIEN_DK, C_ALIEN_DK, C_ALIEN_DK, C_ALIEN_DK, C_ALIEN_MAIN, C_ALIEN_LGT, C_ENG_PURP, C_ALIEN_LGT, C_ALIEN_MAIN, C_ALIEN_MAIN, C_ALIEN_LGT, C_ALIEN_MAIN, C_ALIEN_DK, C_ALIEN_DK, C_ALIEN_MAIN, C_TOXIC_GLW, C_ALIEN_MAIN, C_ALIEN_DK, C_TRANS, C_ALIEN_DK, C_ALIEN_MAIN, C_TOXIC_GLW, C_TRANS,

    // Kolumna 20
    C_ALIEN_DK, C_ALIEN_MAIN, C_ALIEN_DK, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_ALIEN_DK, C_ALIEN_MAIN, C_ENG_PURP, C_ALIEN_MAIN, C_ALIEN_DK, C_ALIEN_DK, C_ALIEN_MAIN, C_TOXIC_GLW, C_TOXIC_GLW, C_TOXIC_GLW, C_ALIEN_MAIN, C_ALIEN_DK, C_TRANS, C_TRANS, C_ALIEN_DK, C_ALIEN_MAIN, C_TOXIC_GLW, C_TRANS, C_TRANS,

    // Kolumna 21
    C_TRANS, C_ALIEN_DK, C_ALIEN_MAIN, C_ALIEN_LGT, C_ALIEN_DK, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_ALIEN_DK, C_ALIEN_MAIN, C_ENG_PURP, C_ALIEN_DK, C_TRANS, C_TRANS, C_ALIEN_DK, C_ALIEN_MAIN, C_TOXIC_GLW, C_ALIEN_MAIN, C_ALIEN_DK, C_TRANS, C_TRANS, C_ALIEN_DK, C_ALIEN_MAIN, C_TOXIC_GLW, C_TOXIC_GLW, C_TRANS, C_TRANS,

    // Kolumna 22
    C_TRANS, C_TRANS, C_ALIEN_DK, C_ALIEN_MAIN, C_ALIEN_LGT, C_ALIEN_DK, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_ALIEN_DK, C_ALIEN_MAIN, C_ALIEN_DK, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_ALIEN_DK, C_ALIEN_MAIN, C_ALIEN_DK, C_TRANS, C_TRANS, C_ALIEN_DK, C_ALIEN_MAIN, C_ALIEN_DK, C_TRANS, C_TOXIC_GLW, C_TOXIC_GLW, C_TRANS,

    // Kolumna 23
    C_TRANS, C_TRANS, C_TRANS, C_ALIEN_DK, C_ALIEN_MAIN, C_ALIEN_LGT, C_ALIEN_MAIN, C_ALIEN_DK, C_ALIEN_DK, C_ALIEN_DK, C_ALIEN_DK, C_ALIEN_MAIN, C_ALIEN_LGT, C_ALIEN_MAIN, C_ALIEN_DK, C_ALIEN_DK, C_ALIEN_DK, C_ALIEN_DK, C_ALIEN_MAIN, C_ALIEN_DK, C_TRANS, C_TRANS, C_ALIEN_DK, C_TRANS, C_TRANS, C_TOXIC_GLW, C_TOXIC_GLW, C_TOXIC_GLW, C_TOXIC_GLW, C_TRANS,

    // Kolumna 24
    C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_ALIEN_DK, C_ALIEN_MAIN, C_ALIEN_MAIN, C_ALIEN_LGT, C_ALIEN_MAIN, C_ALIEN_MAIN, C_ALIEN_MAIN, C_ALIEN_MAIN, C_ALIEN_LGT, C_ALIEN_MAIN, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_ALIEN_MAIN, C_ALIEN_DK, C_TRANS, C_ALIEN_DK, C_ALIEN_MAIN, C_ALIEN_DK, C_TRANS, C_TOXIC_GLW, C_TOXIC_GLW, C_TOXIC_GLW, C_TRANS, C_TRANS,

    // Kolumna 25
    C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_ALIEN_DK, C_ALIEN_MAIN, C_ALIEN_MAIN, C_ALIEN_LGT, C_ALIEN_LGT, C_ALIEN_LGT, C_ALIEN_MAIN, C_ALIEN_MAIN, C_ALIEN_LGT, C_TRANS, C_TRANS, C_ALIEN_LGT, C_ALIEN_MAIN, C_ALIEN_DK, C_ALIEN_DK, C_ALIEN_MAIN, C_ALIEN_LGT, C_ALIEN_MAIN, C_ALIEN_DK, C_TOXIC_GLW, C_TOXIC_GLW, C_TRANS, C_TRANS, C_TRANS,

    // Kolumna 26
    C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_ALIEN_DK, C_ALIEN_DK, C_ALIEN_DK, C_ALIEN_DK, C_ALIEN_DK, C_ALIEN_MAIN, C_ALIEN_MAIN, C_ALIEN_LGT, C_ALIEN_LGT, C_ALIEN_MAIN, C_ALIEN_LGT, C_ALIEN_MAIN, C_ALIEN_MAIN, C_ALIEN_LGT, C_ALIEN_MAIN, C_ALIEN_MAIN, C_ALIEN_DK, C_TOXIC_GLW, C_TRANS, C_TRANS, C_TRANS, C_TRANS,

    // Kolumna 27
    C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_ALIEN_DK, C_ALIEN_DK, C_ALIEN_DK, C_ALIEN_MAIN, C_ALIEN_MAIN, C_ALIEN_LGT, C_ALIEN_LGT, C_ALIEN_MAIN, C_ALIEN_MAIN, C_ALIEN_DK, C_ALIEN_DK, C_ALIEN_DK, C_TOXIC_GLW, C_TOXIC_GLW, C_TRANS, C_TRANS,

    // Kolumna 28
    C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_ALIEN_DK, C_ALIEN_DK, C_ALIEN_DK, C_ALIEN_DK, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TOXIC_GLW, C_TOXIC_GLW, C_TRANS, C_TRANS,

    // Kolumna 29
    C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TOXIC_GLW, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TOXIC_GLW, C_TRANS, C_TRANS, C_TRANS

};
