
#include "player.h"
#include "colors.h"

const uint32_t PLAYER_TEXTURE[] = {

    // Wiersz 0
    C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_SHP_DK, C_SHP_DK, C_SHP_MAIN, C_SHP_MAIN, C_SHP_DK, C_SHP_DK, C_SHP_DK, C_TRANS, C_TRANS,

    // Wiersz 1
    C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_SHP_DK, C_SHP_DK, C_SHP_MAIN, C_SHP_MAIN, C_SHP_MAIN, C_SHP_MAIN, C_SHP_LGHT, C_SHP_MAIN, C_SHP_DK, C_SHP_DK, C_TRANS,

    // Wiersz 2
    C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_SHP_DK, C_SHP_DK, C_SHP_MAIN, C_SHP_MAIN, C_SHP_MAIN, C_SHP_MAIN, C_SHP_LGHT, C_SHP_LGHT, C_SHP_MAIN, C_SHP_MAIN, C_SHP_DK, C_FIRE_RED, C_TRANS,

    // Wiersz 3
    C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_SHP_DK, C_SHP_DK, C_SHP_MAIN, C_SHP_MAIN, C_SHP_MAIN, C_SHP_MAIN, C_SHP_LGHT, C_SHP_MAIN, C_SHP_MAIN, C_SHP_MAIN, C_SHP_DK, C_SHP_DK, C_FIRE_RED, C_FIRE_RED, C_FIRE_DK,

    // Wiersz 4
    C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_SHP_DK, C_SHP_DK, C_SHP_MAIN, C_SHP_MAIN, C_SHP_MAIN, C_SHP_MAIN, C_SHP_MAIN, C_SHP_MAIN, C_SHP_MAIN, C_SHP_DK, C_SHP_DK, C_SHP_DK, C_SHP_DK, C_FIRE_RED, C_FIRE_RED, C_FIRE_RED, C_FIRE_DK,

    // Wiersz 5
    C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_SHP_DK, C_SHP_DK, C_SHP_MAIN, C_SHP_MAIN, C_SHP_MAIN, C_SHP_MAIN, C_SHP_LGHT, C_SHP_MAIN, C_SHP_MAIN, C_SHP_MAIN, C_SHP_DK, C_SHP_DK, C_FIRE_RED, C_FIRE_RED, C_FIRE_RED, C_CORE_GOLD, C_CORE_WHT, C_CORE_GOLD, C_FIRE_RED,

    // Wiersz 6 (Początek nowej sekcji silnikowej)
    C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_SHP_DK, C_SHP_DK, C_SHP_MAIN, C_SHP_MAIN, C_SHP_MAIN, C_SHP_MAIN, C_SHP_MAIN, C_SHP_MAIN, C_SHP_MAIN, C_SHP_LGHT, C_SHP_MAIN, C_SHP_MAIN, C_SHP_DK, C_SHP_DK, C_SHP_DK, C_FIRE_RED, C_FIRE_RED, C_CORE_GOLD, C_CORE_WHT, C_CORE_WHT, C_CORE_WHT, C_CORE_GOLD, C_FIRE_RED, C_FIRE_DK,

    // Wiersz 7 (Lewy silnik)
    C_TRANS, C_FIRE_DK, C_FIRE_RED, C_SHP_DK, C_SHP_MAIN, C_CORE_GOLD, C_CORE_GOLD, C_SHP_MAIN, C_SHP_MAIN, C_SHP_MAIN, C_SHP_MAIN, C_SHP_LGHT, C_SHP_MAIN, C_SHP_MAIN, C_SHP_DK, C_SHP_DK, C_TRANS, C_TRANS, C_SHP_DK, C_SHP_DK, C_FIRE_RED, C_CORE_GOLD, C_CORE_WHT, C_CORE_WHT, C_CORE_GOLD, C_FIRE_RED, C_FIRE_DK, C_TRANS,

    // Wiersz 8
    C_FIRE_DK, C_FIRE_RED, C_CORE_GOLD, C_SHP_DK, C_SHP_MAIN, C_CORE_WHT, C_CORE_WHT, C_CORE_GOLD, C_SHP_MAIN, C_SHP_MAIN, C_SHP_DK, C_SHP_DK, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_SHP_DK, C_SHP_DK, C_FIRE_RED, C_FIRE_RED, C_CORE_GOLD, C_FIRE_RED, C_FIRE_RED, C_FIRE_DK, C_TRANS, C_TRANS,

    // Wiersz 9 (Łącznik skrzydła z kadłubem)
    C_FIRE_RED, C_CORE_GOLD, C_CORE_WHT, C_SHP_DK, C_SHP_MAIN, C_CORE_GOLD, C_CORE_WHT, C_CORE_GOLD, C_SHP_MAIN, C_SHP_DK, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_SHP_DK, C_SHP_DK, C_SHP_DK, C_SHP_DK, C_SHP_DK, C_FIRE_DK, C_TRANS, C_TRANS, C_TRANS,

    // Wiersz 10
    C_FIRE_RED, C_CORE_WHT, C_CORE_WHT, C_SHP_DK, C_SHP_MAIN, C_SHP_MAIN, C_SHP_MAIN, C_SHP_DK, C_SHP_DK, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_SHP_DK, C_SHP_MAIN, C_SHP_MAIN, C_SHP_LGHT, C_SHP_MAIN, C_SHP_DK, C_TRANS, C_TRANS, C_TRANS, C_TRANS,

    // Wiersz 11 (Budowanie nowego dziobu)
    C_SHP_DK, C_SHP_MAIN, C_SHP_MAIN, C_SHP_DK, C_SHP_MAIN, C_SHP_MAIN, C_SHP_MAIN, C_SHP_DK, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_SHP_DK, C_SHP_DK, C_SHP_DK, C_SHP_DK, C_SHP_DK, C_SHP_DK, C_SHP_MAIN, C_SHP_MAIN, C_SHP_LGHT, C_SHP_LGHT, C_SHP_LGHT, C_SHP_MAIN, C_SHP_DK, C_TRANS, C_TRANS, C_TRANS,

    // Wiersz 12
    C_SHP_DK, C_SHP_MAIN, C_SHP_DK, C_TRANS, C_SHP_DK, C_SHP_MAIN, C_SHP_MAIN, C_SHP_DK, C_TRANS, C_TRANS, C_SHP_DK, C_SHP_DK, C_SHP_MAIN, C_SHP_MAIN, C_SHP_MAIN, C_SHP_MAIN, C_SHP_MAIN, C_SHP_MAIN, C_SHP_MAIN, C_SHP_LGHT, C_SHP_LGHT, C_SHP_MAIN, C_SHP_MAIN, C_SHP_LGHT, C_SHP_DK, C_FIRE_DK, C_TRANS, C_TRANS,

    // OŚ ŚRODKOWA (Y=13)
    C_SHP_DK, C_SHP_DK, C_TRANS, C_TRANS, C_SHP_DK, C_SHP_MAIN, C_SHP_MAIN, C_SHP_DK, C_TRANS, C_SHP_DK, C_SHP_MAIN, C_SHP_MAIN, C_CORE_GOLD, C_CORE_WHT, C_CORE_WHT, C_CORE_WHT, C_CORE_GOLD, C_SHP_MAIN, C_SHP_MAIN, C_SHP_LGHT, C_SHP_MAIN, C_SHP_MAIN, C_SHP_LGHT, C_SHP_LGHT, C_SHP_MAIN, C_SHP_DK, C_FIRE_RED, C_TRANS,

    // Wiersz 14 (Lustrzane odbicie w dół)
    C_SHP_DK, C_SHP_DK, C_TRANS, C_TRANS, C_SHP_DK, C_SHP_MAIN, C_SHP_MAIN, C_SHP_DK, C_TRANS, C_SHP_DK, C_SHP_MAIN, C_SHP_MAIN, C_CORE_GOLD, C_CORE_WHT, C_CORE_WHT, C_CORE_WHT, C_CORE_GOLD, C_SHP_MAIN, C_SHP_MAIN, C_SHP_LGHT, C_SHP_MAIN, C_SHP_MAIN, C_SHP_LGHT, C_SHP_LGHT, C_SHP_MAIN, C_SHP_DK, C_FIRE_RED, C_TRANS,

    // Wiersz 15
    C_SHP_DK, C_SHP_MAIN, C_SHP_DK, C_TRANS, C_SHP_DK, C_SHP_MAIN, C_SHP_MAIN, C_SHP_DK, C_TRANS, C_TRANS, C_SHP_DK, C_SHP_DK, C_SHP_MAIN, C_SHP_MAIN, C_SHP_MAIN, C_SHP_MAIN, C_SHP_MAIN, C_SHP_MAIN, C_SHP_MAIN, C_SHP_LGHT, C_SHP_LGHT, C_SHP_MAIN, C_SHP_MAIN, C_SHP_LGHT, C_SHP_DK, C_FIRE_DK, C_TRANS, C_TRANS,

    // Wiersz 16
    C_SHP_DK, C_SHP_MAIN, C_SHP_MAIN, C_SHP_DK, C_SHP_MAIN, C_SHP_MAIN, C_SHP_MAIN, C_SHP_DK, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_SHP_DK, C_SHP_DK, C_SHP_DK, C_SHP_DK, C_SHP_DK, C_SHP_DK, C_SHP_MAIN, C_SHP_MAIN, C_SHP_LGHT, C_SHP_LGHT, C_SHP_LGHT, C_SHP_MAIN, C_SHP_DK, C_TRANS, C_TRANS, C_TRANS,

    // Wiersz 17
    C_FIRE_RED, C_CORE_WHT, C_CORE_WHT, C_SHP_DK, C_SHP_MAIN, C_SHP_MAIN, C_SHP_MAIN, C_SHP_DK, C_SHP_DK, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_SHP_DK, C_SHP_MAIN, C_SHP_MAIN, C_SHP_LGHT, C_SHP_MAIN, C_SHP_DK, C_TRANS, C_TRANS, C_TRANS, C_TRANS,

    // Wiersz 18 (Łącznik skrzydła z kadłubem)
    C_FIRE_RED, C_CORE_GOLD, C_CORE_WHT, C_SHP_DK, C_SHP_MAIN, C_CORE_GOLD, C_CORE_WHT, C_CORE_GOLD, C_SHP_MAIN, C_SHP_DK, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_SHP_DK, C_SHP_DK, C_SHP_DK, C_SHP_DK, C_SHP_DK, C_FIRE_DK, C_TRANS, C_TRANS, C_TRANS,

    // Wiersz 19 (Prawy silnik)
    C_FIRE_DK, C_FIRE_RED, C_CORE_GOLD, C_SHP_DK, C_SHP_MAIN, C_CORE_WHT, C_CORE_WHT, C_CORE_GOLD, C_SHP_MAIN, C_SHP_MAIN, C_SHP_DK, C_SHP_DK, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_SHP_DK, C_SHP_DK, C_FIRE_RED, C_FIRE_RED, C_CORE_GOLD, C_FIRE_RED, C_FIRE_RED, C_FIRE_DK, C_TRANS, C_TRANS,

    // Wiersz 20
    C_TRANS, C_FIRE_DK, C_FIRE_RED, C_FIRE_RED, C_SHP_DK, C_SHP_MAIN, C_SHP_MAIN, C_SHP_MAIN, C_SHP_MAIN, C_SHP_MAIN, C_SHP_MAIN, C_SHP_LGHT, C_SHP_MAIN, C_SHP_MAIN, C_SHP_DK, C_SHP_DK, C_TRANS, C_TRANS, C_SHP_DK, C_SHP_DK, C_FIRE_RED, C_CORE_GOLD, C_CORE_WHT, C_CORE_WHT, C_CORE_GOLD, C_FIRE_RED, C_FIRE_DK, C_TRANS,

    // Wiersz 21 (Koniec nowej sekcji silnikowej)
    C_TRANS, C_TRANS, C_TRANS, C_FIRE_DK, C_FIRE_DK, C_SHP_DK, C_SHP_DK, C_SHP_DK, C_SHP_MAIN, C_SHP_MAIN, C_SHP_MAIN, C_SHP_MAIN, C_SHP_MAIN, C_SHP_LGHT, C_SHP_MAIN, C_SHP_MAIN, C_SHP_DK, C_SHP_DK, C_SHP_DK, C_FIRE_RED, C_FIRE_RED, C_CORE_GOLD, C_CORE_WHT, C_CORE_WHT, C_CORE_WHT, C_CORE_GOLD, C_FIRE_RED, C_FIRE_DK,

    // Wiersz 22
    C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_SHP_DK, C_SHP_DK, C_SHP_MAIN, C_SHP_MAIN, C_SHP_MAIN, C_SHP_MAIN, C_SHP_LGHT, C_SHP_MAIN, C_SHP_MAIN, C_SHP_MAIN, C_SHP_DK, C_SHP_DK, C_FIRE_RED, C_FIRE_RED, C_FIRE_RED, C_CORE_GOLD, C_CORE_WHT, C_CORE_GOLD, C_FIRE_RED,

    // Wiersz 23
    C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_SHP_DK, C_SHP_DK, C_SHP_MAIN, C_SHP_MAIN, C_SHP_MAIN, C_SHP_MAIN, C_SHP_MAIN, C_SHP_MAIN, C_SHP_MAIN, C_SHP_DK, C_SHP_DK, C_SHP_DK, C_SHP_DK, C_FIRE_RED, C_FIRE_RED, C_FIRE_RED, C_FIRE_DK,

    // Wiersz 24
    C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_SHP_DK, C_SHP_DK, C_SHP_MAIN, C_SHP_MAIN, C_SHP_MAIN, C_SHP_MAIN, C_SHP_LGHT, C_SHP_MAIN, C_SHP_MAIN, C_SHP_MAIN, C_SHP_DK, C_SHP_DK, C_FIRE_RED, C_FIRE_RED, C_FIRE_DK,

    // Wiersz 25
    C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_SHP_DK, C_SHP_DK, C_SHP_MAIN, C_SHP_MAIN, C_SHP_MAIN, C_SHP_MAIN, C_SHP_LGHT, C_SHP_LGHT, C_SHP_MAIN, C_SHP_MAIN, C_SHP_DK, C_FIRE_RED, C_TRANS,

    // Wiersz 26
    C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_SHP_DK, C_SHP_DK, C_SHP_MAIN, C_SHP_MAIN, C_SHP_MAIN, C_SHP_MAIN, C_SHP_LGHT, C_SHP_MAIN, C_SHP_DK, C_SHP_DK, C_TRANS,

    // Wiersz 27
    C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_SHP_DK, C_SHP_DK, C_SHP_MAIN, C_SHP_MAIN, C_SHP_DK, C_SHP_DK, C_SHP_DK, C_TRANS, C_TRANS

};


